org: lehcode
app: starter-ui
service: starter-ui
frameworkVersion: ^2.21.1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: local
  memorySize: 192
  region: eu-central-1
  role: lambda-full-access-role

package:
  exclude:
    - .idea/
    - .git/**
    - test/**
    - e2e/**
    - README.md

custom:
  apigwBinary:
    types:
      - "*/*"

functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any
