image: node:10.15.3

pipelines:
  default:
    - parallel:
        - step:
            name: Lint API Application
            caches:
              - node
            script:
              - cd ./api
              - NODE_ENV=production
              - npm install
              - npm run lint
        - step:
            name: Test and Build API Application
            caches:
              - node
            script:
              - cd ./api
              - npm install -g @nestjs/cli
              - npm install
              - NODE_ENV=test npm run test
              - NODE_ENV=production npm run build
        - step:
            name: Lint UI Application
            caches:
              - node
            script:
              - cd ./ui
              - NODE_ENV=production
              - npm install
              - npm run lint-ci
        - step:
            name: Test and Build UI Documentation
            caches:
              - node
            script:
              - cd ./ui
              - npm install -g @angular/cli
              - npm install
              - NODE_ENV=test npm run test
              - NODE_ENV=test npm run e2e
              - npm run doc
        - step:
            name: Build UI Application
            caches:
              - node
            script:
              - npm install -g @angular/cli
              - npm install
              - NODE_ENV=production npm run ssr-build
