image: node:10.15.3

pipelines:
  default:
    - parallel:
        - step:
            name: Lint API
            caches:
              - node
            script:
              - cd ./api
              - npm install -g @angular/cli
              - npm install
              - npm run lint
        - step:
            name: Test and Build API
            caches:
              - node
            script:
              - cd ./api
              - npm install -g @angular/cli
              - npm install
              - npm run test
              - npm run build
