version: "3.8"

services:
  api:
    image: carvin/api:test
    container_name: carvin-api-test
    environment:
      MONGO_DB: carvin-test
      MONGO_HOST: carvin-mongo-test
      MONGO_PARAMS: "authSource=admin&ssl=true"
      MONGO_PASS: Dev_Pass123
      MONGO_USER: carvinTest
      NODE_ENV: test
    command: "yarn test"
    tty: false

  front:
    image: carvin/front:test
    container_name: carvin-ui-test
    environment:
      NODE_ENV: test
    command: "yarn test"
    tty: false

  mongo:
    container_name: carvin-mongo-test
    environment:
      MONGO_INITDB_DATABASE: carvin-test
      MONGO_INITDB_ROOT_PASSWORD: Dev_Pass123
      MONGO_INITDB_ROOT_USERNAME: carvinTest
