version: "3.8"

# This docker-compose file is used to configure services for the Starter project.
# The services configured here include that of an API server, a UI frontend, and MongoDB.
# The API service uses a Dockerfile located in the docker-assets/api-v1/ folder to create the image. It's command line arguments include a workdir to the API work directory, a Node version to use, and a Nestjs version to use. Environment variables are also set in the environment section providing access to AWS services, ports and MongoDB credentials.
# The front service uses a Dockerfile located in the docker-assets/ui-v1/ folder to create the image. It's command line arguments include a workdir to the UI work directory, a Node version to use, and an Angular version to use. Environment variables are also set in the environment section providing access to ports and Node environment.
# The mongo service uses a .env file located in the docker-assets/mongo/ folder to configure environment variables. It's command line argument include a Mongo version to use and a timezone to use.
# Volumes and networks are also configured allowing for persistent data storage and connectivity between containers.

services:
  # API Service
  api:
    image: starter/api:dev
    container_name: starter-api-dev
    hostname: starter-api
    command: /bin/bash /init.sh
    build:
      context: ./docker-assets/api-v1/
      args:
        workdir: ${API_WORKDIR:?Environment variable API_WORKDIR not specified}
        tz: ${TZ:-Etc/UTC}
        node_version: ${NODE_VERSION:?Environment variable NODE_VERSION not specified}
        node_env: ${NODE_ENV:?Environment variable NODE_ENV not specified}
        nestjs_version: ${NESTJS_CLI_VERSION:?Environment variable NESTJS_VERSION not specified}
        debug: ${DEBUG:-no}
    environment:
      API_PORT: ${API_PORT:-3000}
      MONGO_DB: ${MONGO_DB:?Environment variable MONGO_DB not specified}
      MONGO_HOST: ${MONGO_HOST:-127.0.0.1}
      MONGO_URL_PARAMS: ${MONGO_URL_PARAMS:-?retryWrites=true&w=majority}
      MONGO_PASS: ${MONGO_PASS:?Environment variable MONGO_PASS not specified}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_USER: ${MONGO_USER:?Environment variable MONGO_USER not specified}
      NODE_ENV: ${NODE_ENV:?Environment variable NODE_ENV not specified}
      NODE_VERSION: ${NODE_VERSION:?Environment variable NODE_VERSION not specified}
      AWS_REGION: ${AWS_REGION:-eu-central-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    tty: true
    volumes:
      - ./apps/api:${API_WORKDIR:?Environment variable API_WORKDIR not specified}
    ports:
      - "3000:3000"
      - "3443:3443"
      - "9229:9229"
    depends_on:
      - mongo
      - redis
      - mysql
    networks:
      - starternet

  # UI Frontend Service
  ui:
    image: starter/ui:dev
    container_name: starter-ui-dev
    command: /bin/bash /init.sh
    build:
      context: ./docker-assets/ui-v1/
      args:
        workdir: ${UI_WORKDIR:?Environment variable UI_WORKDIR not specified}
        tz: ${TZ:-Etc/UTC}
        angular_version: ${ANGULAR_CLI_VERSION:?Environment variable USE_ANGULAR_VERSION not specified}
        node_version: ${NODE_VERSION:?Environment variable NODE_VERSION not specified}
        debug: ${DEBUG:-no}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      ANALYTICS_REPORTING: false
    tty: true
    volumes:
      - ./apps/ui:${UI_WORKDIR:?Environment variable UI_WORKDIR not specified}
    ports:
      - "4000:4000"
      - "4200:4200"
      - "4300:4300"
      - "9222:9222"
    depends_on:
      - api
    networks:
      - starternet

  # MongoDB Service
  mongo:
    image: starter/mongo:${MONGO_VERSION}
    container_name: starter-mongo
    hostname: mongo
    command: mongod --auth --port ${MONGO_PORT:-27017} --wiredTigerCacheSizeGB 1.5
    build:
      context: ./docker-assets/mongo/
      shm_size: 500m
      args:
        mongo_version: ${MONGO_VERSION:?Environment variable MONGO_VERSION not specified}
        tz: ${TZ:-Etc/UTC}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:?Specify MONGO_USER environment variable}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:?Specify MONGO_PASS environment variable}
      MONGO_INITDB_DATABASE: ${MONGO_DB:?Specify MONGO_DB environment variable}
    ulimits:
      nproc: 65535
      nofile:
        soft: 64000
        hard: 128000
    volumes:
      - data_db_mongodb:/data/db
      - var_lib_mongodb:/var/lib/mongodb
      - var_log_mongodb:/var/log/mongodb
    ports:
      - "27017:27017"
    networks:
      - starternet
    restart: always

  # Redis Caching Service
  redis:
    image: starter/redis:${REDIS_VERSION}
    hostname: redis
    container_name: starter-redis
    build:
      context: ./docker-assets/redis/
      args:
        tz: ${TZ:-Etc/UTC}
    sysctls:
      net.core.somaxconn: 1024
    command: /bin/bash /init.sh
    ports:
      - "6379:6379"
    volumes:
      - redis_data_bases:/data/bases
      - ./docker-assets/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - starternet
    restart: always

  # MySQL Database Service
  mysql:
    hostname: mysql
    image: starter/mysql:${MYSQL_VERSION}
    build:
      context: ./docker-assets/mysql/
      args:
        mysql_version: ${MYSQL_VERSION:?Specify MYSQL_VERSION environment variable}
    environment:
      MYSQL_ROOT_USER: ${MYSQL_PASS:?Specify MYSQL_USER environment variable}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS:?Specify MYSQL_PASS environment variable}
    volumes:
      - ./docker-assets/mysql/my.cnf:/etc/mysql/my.cnf
    restart: always

# Specify volumes
volumes:
  data_db_mongodb:
  var_lib_mongodb:
  var_log_mongodb:
  redis_data_bases:

# Specify networks
networks:
  starternet:
    ipam:
      driver: default
      config:
        - subnet: 172.16.50.0/24
