version: "3.8"

services:
  mysql:
    image: carvin/mysql:latest
    container_name: "carvin_mysql"
    build:
      context: ./docker-assets/mysql
      args:
        tz: Etc/UTC
      shm_size: "2gb"
    environment:
      MYSQL_ROOT_PASSWORD: "127656"
      MYSQL_ROOT_HOST: "%"
      TZ: Etc/UTC
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    tty: true
    ports:
      - "0.0.0.0:3306:3306"
      - "0.0.0.0:33060:33060"
    env_file: ./docker-assets/mysql/.env
    volumes:
      - var_lib_mysql:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
#    networks:
#      - db_net

volumes:
  var_lib_mysql:
  var_log_mysql:

