version: "3.8"

services:
  api:
    image: carvin/api:test
    build:
      args:
        node_env: test
    container_name: "carvin_api_test"
    environment:
      NODE_ENV: test
    command: yarn test

  front:
    image: carvin/front:test
    build:
      args:
        node_env: test
    container_name: "carvin_ui_test"
    environment:
      NODE_ENV: test
    command: yarn test
