org: lehcode
app: carvin-api
service: carvin-api
frameworkVersion: ^2.21.1

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs10.x
  stage: local
  region: eu-central-1

  environment:
    MONGO_HOST: "localhost"
    MONGO_PORT: 27017
    MONGO_DB: "carvin"
    MONGO_USER: dev
    MONGO_PASS: "devpass123!"
    MONGO_PARAMS: "?authSource=admin&ssl=false&w=majority&readPreference=primary&retryWrites=true"

package:
  exclude:
    - .idea/
    - .git/**
    - test/**
    - e2e/**
    - README.md

functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
          cors: true
          path: '/{any+}'
          method: any
#      - http:
#          cors: true
#          path: '{proxy+}'
#          method: any
